### ISSUE TITLE
g++: error: unrecognized command line option ‘-std=gnu++14’

### ISSUE THREAD

**Issue by whatwewant** [zmicro-design/package-gcc#1]
```bash
> cnpm i -g @cliz/web-terminal
```

```bash
execute post install 1 scripts...
[1/1] scripts.install node-pty@^0.10.1 run "node scripts/install.js", root: "/root/.node/lib/node_modules/@cliz/web-terminal/node_modules/_node-pty@0.10.1@node-pty"
make: Entering directory `/root/.node/lib/node_modules/@cliz/web-terminal/node_modules/_node-pty@0.10.1@node-pty/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
g++: error: unrecognized command line option ‘-std=gnu++14’
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 1
make: Leaving directory `/root/.node/lib/node_modules/@cliz/web-terminal/node_modules/_node-pty@0.10.1@node-pty/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.node/lib/node_modules/cnpm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Linux 3.10.0-1160.45.1.el7.x86_64
gyp ERR! command "/data/plugins/nvm/versions/v16.14.2/bin/node" "/root/.node/lib/node_modules/cnpm/node_modules/npminstall/node-gyp-bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/.node/lib/node_modules/@cliz/web-terminal/node_modules/_node-pty@0.10.1@node-pty
gyp ERR! node -v v16.14.2
gyp ERR! node-gyp -v v9.0.0
gyp ERR! not ok 
[npminstall:runscript:error] node-pty@^0.10.1 scripts.install run "node scripts/install.js" error: Error [RunScriptError]: Run "sh -c node scripts/install.js" error, exit code 1
    at ChildProcess.<anonymous> (/root/.node/lib/node_modules/cnpm/node_modules/runscript/index.js:96:21)
    at ChildProcess.emit (node:events:526:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12) {
  stdio: [Object],
  exitcode: 1
}
Install fail! RunScriptError: post install error, please remove node_modules before retry!
Run "sh -c node scripts/install.js" error, exit code 1
RunScriptError: Run "sh -c node scripts/install.js" error, exit code 1
    at ChildProcess.<anonymous> (/root/.node/lib/node_modules/cnpm/node_modules/runscript/index.js:96:21)
    at ChildProcess.emit (node:events:526:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npminstall version: 6.2.0
npminstall args: /data/plugins/nvm/versions/v16.14.2/bin/node /root/.node/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js --fix-bug-versions --china --userconfig=/root/.cnpmrc --disturl=https://npmmirror.com/mirrors/node --registry=https://registry.npmmirror.com -g @cliz/web-terminal
```

**Comment by whatwewant** [comment]
```bash
Internet:  Disconnected
Operating System Type :  GNU/Linux
OS Version :  Linux RedHat 7.9.2009(Core 3.10.0-1160.45.1.el7.x86_64 x86_64)
Architecture :  x86_64
Kernel Release :  3.10.0-1160.45.1.el7.x86_64
Hostname :  frontend
Internal IP :  10.1.0.169 172.17.0.1 172.18.0.1
External IP :  106.14.46.45
Name Servers :  generated 100.100.2.136 100.100.2.138
Logged In users : 
dev      pts/1        2022-07-08 18:59 (172.18.0.3)
root     pts/7        2022-08-05 14:51 (10.28.103.50)
Ram Usages : 
              total        used        free      shared  buff/cache   available
Mem:            15G        2.9G        351M        1.8M         12G         12G
Swap Usages : 
              total        used        free      shared  buff/cache   available
Swap:          8.0G          0B        8.0G
Disk Usages : 
Filesystem      Size  Used Avail Use% Mounted on
Load Average :  loadaverage:1.07,
System Uptime Days/(HH:MM) :  213 days
```

**Comment by whatwewant** [comment]
related https://github.com/microsoft/node-pty/issues/370

**Comment by whatwewant** [comment]
Trying Build GCC FROM SOURCE with `BUILD_FROM_SOURCE=true zmicro package install gcc`

**Comment by whatwewant** [comment]
> Trying Build GCC FROM SOURCE with `BUILD_FROM_SOURCE=true zmicro package install gcc`

works
