### ISSUE TITLE
/usr/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found  when run `web-terminal --help`

### ISSUE THREAD

**Issue by whatwewant** [zmicro-design/package-gcc#2]
```bash
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /root/.node/lib/node_modules/@cliz/web-terminal/node_modules/node-pty/lib/unixTerminal.js
- /root/.node/lib/node_modules/@cliz/web-terminal/node_modules/node-pty/lib/index.js
- /root/.node/lib/node_modules/@cliz/web-terminal/lib/core/simple/terminal.js
- /root/.node/lib/node_modules/@cliz/web-terminal/lib/core/simple/ws.js
- /root/.node/lib/node_modules/@cliz/web-terminal/lib/core/simple/index.js
- /root/.node/lib/node_modules/@cliz/web-terminal/lib/commands/simple.js
- /root/.node/lib/node_modules/@cliz/web-terminal/node_modules/@caporal/core/dist/index.js
- /root/.node/lib/node_modules/@cliz/web-terminal/node_modules/@cliz/core/lib/core/createMultiCommandsProgram.js
- /root/.node/lib/node_modules/@cliz/web-terminal/node_modules/@cliz/core/lib/core/index.js
- /root/.node/lib/node_modules/@cliz/web-terminal/node_modules/@cliz/core/lib/index.js
- /root/.node/lib/node_modules/@cliz/web-terminal/node_modules/@cliz/cli/lib/index.js
- /root/.node/lib/node_modules/@cliz/web-terminal/lib/cli.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/root/.node/lib/node_modules/@cliz/web-terminal/node_modules/node-pty/lib/unixTerminal.js:31:15)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/root/.node/lib/node_modules/@cliz/web-terminal/node_modules/node-pty/lib/index.js:13:20)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/.node/lib/node_modules/@cliz/web-terminal/node_modules/node-pty/lib/unixTerminal.js',
    '/root/.node/lib/node_modules/@cliz/web-terminal/node_modules/node-pty/lib/index.js',
    '/root/.node/lib/node_modules/@cliz/web-terminal/lib/core/simple/terminal.js',
    '/root/.node/lib/node_modules/@cliz/web-terminal/lib/core/simple/ws.js',
    '/root/.node/lib/node_modules/@cliz/web-terminal/lib/core/simple/index.js',
    '/root/.node/lib/node_modules/@cliz/web-terminal/lib/commands/simple.js',
    '/root/.node/lib/node_modules/@cliz/web-terminal/node_modules/@caporal/core/dist/index.js',
    '/root/.node/lib/node_modules/@cliz/web-terminal/node_modules/@cliz/core/lib/core/createMultiCommandsProgram.js',
    '/root/.node/lib/node_modules/@cliz/web-terminal/node_modules/@cliz/core/lib/core/index.js',
    '/root/.node/lib/node_modules/@cliz/web-terminal/node_modules/@cliz/core/lib/index.js',
    '/root/.node/lib/node_modules/@cliz/web-terminal/node_modules/@cliz/cli/lib/index.js',
    '/root/.node/lib/node_modules/@cliz/web-terminal/lib/cli.js'
  ]
}

error: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /root/.node/lib/node_modules/@cliz/web-terminal/node_modules/node-pty/build/Release/pty.node)
```

**Comment by whatwewant** [comment]
fixed with: `ln -sf /usr/local/gcc/lib64/libstdc++.so.6.0.30 /usr/lib64/libstdc++.so.6`

**Comment by whatwewant** [comment]
related: https://github.com/zcorky/cliz/issues/99
